### ISSUE TITLE
Can't drag and drop multiple files at once in Windows 10

### ISSUE THREAD

**Issue by ghost** [szTheory/exifcleaner#139]
When I try to drag multiple files over to clean metadata faster it does not give me a prompt to drop it into the box. I was wondering if it could be possible for the program to handle multiple files at once.

**Comment by szTheory** [comment]
It should work with multiple files at once using drag and drop. What OS are you on?

**Comment by Flam3z** [comment]
Windows 10

**Comment by szTheory** [comment]
I'm not sure if it supports dragging in a folder. Try going into a folder and dragging multiple files in from there. What happens when you do that? Does it only pick one or something? If that doesn't work maybe you can upload a screenshot or a video.

**Comment by Flam3z** [comment]
I tried dragging them from a folder, didn't work then I tried selecting them from within the program "open" option.

**Comment by szTheory** [comment]
Sorry not sure what the issue could be. Maybe try reinstalling the program, or drag files directly instead of from a folder, or drag different files if it's perhaps a permissions issue of some kind.

**Comment by Flam3z** [comment]
I tried different files and file types (jpg, png mp4) and the same issue would still occur.

**Comment by szTheory** [comment]
I've just released a new version 3.5.0. I didn't change anything that I think would fix this issue, but maybe you can download it and give it a try again with that new version.

**Comment by Flam3z** [comment]
I tried the latest version and it just says "cannot open multiple items from this location. Try selecting a single item instead" i used the "open" method since dragging it still doesn't work.

**Comment by szTheory** [comment]
Hmm sorry to hear that. Hopefully I can reproduce this sometime in the future and fix it. In the meantime you could try opening the chrome developer tools while drag and dropping, and seeing if there are any Javascript errors in the console tab.

**Comment by Flam3z** [comment]
I found something interesting, I am able to select and drag multiple photos that are on my pc. But it does not allow me to do that from when I try to do the same actions from my phone.

**Comment by szTheory** [comment]
Oh interesting. Are you saying you have ExifCleaner running on your phone? Or are you dragging photos from your USB or whatever connected phone using Windows File Explorer?

**Comment by Flam3z** [comment]
Dragging files from my phone using windows file explorer.

**Comment by szTheory** [comment]
Worth a retest on **v4.0.0** — https://github.com/szTheory/exifcleaner/releases

Drag-and-drop was rewritten for this release. The old code read `file.path`, which Electron removed when the renderer became sandboxed; it now goes through `webUtils.getPathForFile()` via the preload bridge. Multi-file drops are covered by E2E tests.

This is a five-year-old report against a very different codebase, so I'd rather not guess. If it still misbehaves, a comment here with your OS version is enough to reopen it.

**Comment by szTheory** [comment]
ExifCleaner 4.0.1 is now available: https://github.com/szTheory/exifcleaner/releases/tag/v4.0.1

Please retest dragging multiple files on Windows 10 with this exact version. If there is no update by **2026-09-01**, this issue will be closed as stale; a later reproduction can still be reported.

**Comment by szTheory** [comment]
Closing this one, and I want to be explicit about why rather than let it expire silently.

On 2026-08-02 I wrote here: "If there is no update by **2026-09-01**, this issue will be closed
as stale; a later reproduction can still be reported." That date has passed with no update.

**What I checked:** `src/renderer/components/ui/DropZone.tsx:233-242` (`handleDrop`) and
`tests/e2e/file-processing.spec.ts:115` — test "processes a batch of 3 mixed file types"
**Result:** The current drop handler maps every file in the drag event
(`Array.from(e.dataTransfer.files)`) through `window.api.files.getPathForFile()` — which bridges
to Electron's `webUtils.getPathForFile` in `src/preload/index.ts:85` — and processes the full
set, not just one. That is the v4.0 drag-and-drop rewrite already mentioned in this thread. The
batch-processing E2E test exercises multiple files through the same intake path and passes on
the current release.
**Not established:** I have not reproduced the original Windows 10 multi-file drag-and-drop
failure, and I have no confirmed cause for it. Nothing here should be read as an explanation of
what went wrong on your machine — the traced code above shows what the current release does in
general, not a diagnosis of your specific report.

**This is not a rejection.** It means I have no evidence I can act on. A comment on this issue
reopens it at any point — there is no time limit, and you do not need to say anything more than
"still happening on version X, OS Y".
